## CHANGE this to the name of your plugin.
name: PotionExpansion

## CHANGE this to your username.
author: EpicPlayerA10

## CHANGE this to a meaninful but short description of your plugin.
description: An addon for slimefun that adds new potions to the game!

## CHANGE this to the path of the class that extends JavaPlugin.
main: com.epicplayera10.potionexpansion.PotionExpansion

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/EpicPlayerA10/PotionExpansion

## This value is automatically replaced by the version specified in your pom.xml file.
## Do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.14

## This is required and marks Slimefun as a plugin dependency.
depend:
- Slimefun

softdepend:
  - ProtocolLib

commands:
  potionexpansion:
    description: Main command of this addon.
    aliases: [pe]