name: Java CI

on:
  push:
    paths:
    - 'src/**'
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    name: Build Plugin

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: 16
    - name: Build with Maven
      run: mvn package --file pom.xml
