name: Build Pull Request

on: 
  push:

    branches: [ master ]
# 注意一下，这个是分支名 可能是main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
# jdk 设置 
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
# 1.8 = Java8 可以直接写8 
# 一些拓展的版本可能是11 或16
      - name: submodules-init
        uses: snickerbockers/submodules-init@v4
      - name: Build with Maven
        run: mvn -B package -T 2C
      - name: Archive artifacts (artifacts)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: PotionExpansion zh-CN
          path: target/PotionExpansion v4 zh-CN.jar
# 注意要和打包出来的一致
# 注意要和打包出来的一致
